### ISSUE TITLE
ePub code formatting is not using monospaced font

### ISSUE THREAD

**Issue by moltar** [GraphQLGuide/graphql-rest-api-demo#3]
Seems like a mix of different fonts: http://take.ms/JEheo

Using iBooks on latest macOS.

**Comment by lorensr** [comment]
Issue moved to [GraphQLGuide/book #5](https://github.com/GraphQLGuide/book/issues/5) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lorensr** [comment]
Thanks for reporting, Roman—haven't figured out why gitbook is doing that yet!
